### ISSUE TITLE
Logo not loading

### ISSUE THREAD

**Issue by browsermage** [MajorJohnDoe/flappyfish#1]
What an incredible game! Unfortunately, the logo didn't load as expected. I've attached a screenshot to highlight the issue:

<img width="840" alt="image" src="https://github.com/MajorJohnDoe/flappyfish/assets/7055622/fb7fc40b-d737-4de7-ab5c-e1af492f8daf">

**Comment by MajorJohnDoe** [comment]
Fixed!
